#!/bin/sh
echo "SpriteTextures..."
cp -fr SpriteTextures-M1 ../M1A1
mv -f ../M1A1/SpriteTextures-M1/Sprites.mml ../M1A1/Scripts
echo "TTEP-M1..."
cp -fr TTEP-M1 ../M1A1
echo "StandardTextures-M1..."
cp -fr StandardTextures-M1 ../M1A1
